name: prestashop

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php-version: '5.6'
            branch: '1.7.4.0'
            composerv1: 1
            phpunit-version: 'phpunit:5.7'

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: composer:v2, ${{ matrix.phpunit-version }}
          extensions: gd, mbstring, zip, mcrypt, pdo_mysql, dom
      - name: Start mysql service
        run: sudo /etc/init.d/mysql start
      - name: Status mysql service
        run: sudo systemctl status mysql
      - name: Test MySQL Connection
        run: mysql -u root -h '127.0.0.1' --port ${{ job.services.mysql.ports['3306'] }} -e "show databases"
      - name: Install PrestaShop
        env:
          BRANCH: ${{ matrix.branch }}
          COMPOSERV1: ${{ matrix.composerv1 }}
          MYSQL_PORT: ${{ job.services.mysql.ports['3306'] }}
        run: make before_script
      - name: Set-up .env
        run: |
          echo '{"github-oauth": {"github.com": "${{ secrets.GH_REPO_ALLOWED_TOKEN }}"}}' > $GITHUB_WORKSPACE/auth.json
      - name: Run tests
        env:
          BRANCH: ${{ matrix.branch }}
          COMPOSERV1: ${{ matrix.composerv1 }}
        run: make test
      - name: Coverage
        env:
          COVERAGE: ${{ matrix.coverage }}
        if: env.COVERAGE == 1
        run: |
          make coverage
          bash <(curl -s https://codecov.io/bash)

  deploy:
    needs: ['test']
    if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP 5.6
        uses: shivammathur/setup-php@v2
        with:
          php-version: '5.6'
          tools: composer:v1
      - name: Set-up .env
        run: |
          echo '{"github-oauth": {"github.com": "${{ secrets.GH_REPO_ALLOWED_TOKEN }}"}}' > $GITHUB_WORKSPACE/auth.json
      - name: Build release
        run: |
          git fetch origin --unshallow --tags
          export LAST_TAG=`git describe --abbrev=0 --tags`
          export VERSION=`grep -Eo "version = '(.*)'" ./shoparizepartner.php | grep -Eo '([0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2})'`
          export ARCHIVE_NAME=shoparizepartner-$VERSION.zip
          export ARCHIVE_PATH="/tmp/$ARCHIVE_NAME"
          export RELEASE_TAG=$VERSION
          export LAST_COMMIT=`git log --oneline --format=%B -n 1 HEAD | head -n 1`
          echo RELEASE_TAG=$RELEASE_TAG >> $GITHUB_ENV
          echo LAST_TAG=$LAST_TAG >> $GITHUB_ENV
          echo LAST_COMMIT=$LAST_COMMIT >> $GITHUB_ENV
          echo ARCHIVE_PATH=$ARCHIVE_PATH >> $GITHUB_ENV
          echo ARCHIVE_NAME=$ARCHIVE_NAME >> $GITHUB_ENV
          make build_archive
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        if: env.LAST_TAG != env.RELEASE_TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: ${{ env.RELEASE_TAG }}
          body: ${{ env.LAST_COMMIT }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        if: env.LAST_TAG != env.RELEASE_TAG
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ARCHIVE_PATH }}
          asset_name: ${{ env.ARCHIVE_NAME }}
          asset_content_type: application/zip
      - name: Deploy
        run: make build_archive
      - name: Cleanup
        if: env.LAST_TAG != env.RELEASE_TAG
        run: make delete_archive
